"""add_a2a_session_continuity_tables

Revision ID: 31f69b1d0dc5
Revises: d1071201185f
Create Date: 2025-07-18 23:59:09.795850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31f69b1d0dc5'
down_revision: Union[str, Sequence[str], None] = 'd1071201185f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('a2a_contexts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('context_id', sa.String(length=255), nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=True),
    sa.Column('agent_name', sa.String(length=100), nullable=False),
    sa.Column('conversation_history', sa.JSON(), nullable=True),
    sa.Column('agent_state', sa.JSON(), nullable=True),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_a2a_contexts_agent_name'), 'a2a_contexts', ['agent_name'], unique=False)
    op.create_index(op.f('ix_a2a_contexts_context_id'), 'a2a_contexts', ['context_id'], unique=True)
    op.create_index(op.f('ix_a2a_contexts_id'), 'a2a_contexts', ['id'], unique=False)
    op.create_index(op.f('ix_a2a_contexts_session_id'), 'a2a_contexts', ['session_id'], unique=False)
    op.create_table('a2a_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.String(length=255), nullable=False),
    sa.Column('context_id', sa.String(length=255), nullable=False),
    sa.Column('parent_task_id', sa.String(length=255), nullable=True),
    sa.Column('kind', sa.String(length=50), nullable=False),
    sa.Column('status_state', sa.String(length=50), nullable=False),
    sa.Column('status_message', sa.JSON(), nullable=True),
    sa.Column('initial_message', sa.JSON(), nullable=True),
    sa.Column('artifacts', sa.JSON(), nullable=True),
    sa.Column('message_history', sa.JSON(), nullable=True),
    sa.Column('agent_name', sa.String(length=100), nullable=False),
    sa.Column('execution_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('execution_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_details', sa.Text(), nullable=True),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['context_id'], ['a2a_contexts.context_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_a2a_tasks_agent_name'), 'a2a_tasks', ['agent_name'], unique=False)
    op.create_index(op.f('ix_a2a_tasks_context_id'), 'a2a_tasks', ['context_id'], unique=False)
    op.create_index(op.f('ix_a2a_tasks_id'), 'a2a_tasks', ['id'], unique=False)
    op.create_index(op.f('ix_a2a_tasks_parent_task_id'), 'a2a_tasks', ['parent_task_id'], unique=False)
    op.create_index(op.f('ix_a2a_tasks_status_state'), 'a2a_tasks', ['status_state'], unique=False)
    op.create_index(op.f('ix_a2a_tasks_task_id'), 'a2a_tasks', ['task_id'], unique=True)
    op.create_table('a2a_agent_interactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('interaction_id', sa.String(length=255), nullable=False),
    sa.Column('task_id', sa.String(length=255), nullable=False),
    sa.Column('client_agent', sa.String(length=100), nullable=False),
    sa.Column('remote_agent', sa.String(length=100), nullable=False),
    sa.Column('remote_agent_url', sa.String(length=500), nullable=True),
    sa.Column('interaction_type', sa.String(length=50), nullable=False),
    sa.Column('request_message', sa.JSON(), nullable=True),
    sa.Column('response_message', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['a2a_tasks.task_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_a2a_agent_interactions_client_agent'), 'a2a_agent_interactions', ['client_agent'], unique=False)
    op.create_index(op.f('ix_a2a_agent_interactions_id'), 'a2a_agent_interactions', ['id'], unique=False)
    op.create_index(op.f('ix_a2a_agent_interactions_interaction_id'), 'a2a_agent_interactions', ['interaction_id'], unique=True)
    op.create_index(op.f('ix_a2a_agent_interactions_interaction_type'), 'a2a_agent_interactions', ['interaction_type'], unique=False)
    op.create_index(op.f('ix_a2a_agent_interactions_remote_agent'), 'a2a_agent_interactions', ['remote_agent'], unique=False)
    op.create_index(op.f('ix_a2a_agent_interactions_status'), 'a2a_agent_interactions', ['status'], unique=False)
    op.create_index(op.f('ix_a2a_agent_interactions_task_id'), 'a2a_agent_interactions', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_a2a_agent_interactions_task_id'), table_name='a2a_agent_interactions')
    op.drop_index(op.f('ix_a2a_agent_interactions_status'), table_name='a2a_agent_interactions')
    op.drop_index(op.f('ix_a2a_agent_interactions_remote_agent'), table_name='a2a_agent_interactions')
    op.drop_index(op.f('ix_a2a_agent_interactions_interaction_type'), table_name='a2a_agent_interactions')
    op.drop_index(op.f('ix_a2a_agent_interactions_interaction_id'), table_name='a2a_agent_interactions')
    op.drop_index(op.f('ix_a2a_agent_interactions_id'), table_name='a2a_agent_interactions')
    op.drop_index(op.f('ix_a2a_agent_interactions_client_agent'), table_name='a2a_agent_interactions')
    op.drop_table('a2a_agent_interactions')
    op.drop_index(op.f('ix_a2a_tasks_task_id'), table_name='a2a_tasks')
    op.drop_index(op.f('ix_a2a_tasks_status_state'), table_name='a2a_tasks')
    op.drop_index(op.f('ix_a2a_tasks_parent_task_id'), table_name='a2a_tasks')
    op.drop_index(op.f('ix_a2a_tasks_id'), table_name='a2a_tasks')
    op.drop_index(op.f('ix_a2a_tasks_context_id'), table_name='a2a_tasks')
    op.drop_index(op.f('ix_a2a_tasks_agent_name'), table_name='a2a_tasks')
    op.drop_table('a2a_tasks')
    op.drop_index(op.f('ix_a2a_contexts_session_id'), table_name='a2a_contexts')
    op.drop_index(op.f('ix_a2a_contexts_id'), table_name='a2a_contexts')
    op.drop_index(op.f('ix_a2a_contexts_context_id'), table_name='a2a_contexts')
    op.drop_index(op.f('ix_a2a_contexts_agent_name'), table_name='a2a_contexts')
    op.drop_table('a2a_contexts')
    # ### end Alembic commands ###
