"""add task_id to message and auto-create conversation

Revision ID: d1071201185f
Revises: 
Create Date: 2025-07-06 18:26:48.262112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1071201185f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add root_id to conversations
    op.add_column('conversations', sa.Column('root_id', sa.String(length=255), nullable=True))
    op.create_index('ix_conversations_root_id', 'conversations', ['root_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove root_id from conversations
    op.drop_index('ix_conversations_root_id', table_name='conversations')
    op.drop_column('conversations', 'root_id')
    # ### end Alembic commands ###
