"""add task_id to message and auto-create conversation

Revision ID: d1071201185f
Revises: 
Create Date: 2025-07-06 18:26:48.262112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1071201185f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('task_id', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_messages_task_id'), 'messages', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_task_id'), table_name='messages')
    op.drop_column('messages', 'task_id')
    # ### end Alembic commands ###
