version: "3.9"

services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j-data:/data
    environment:
      - NEO4J_AUTH=neo4j/password
    networks:
      - tron-ai-network

networks:
  tron-ai-network:
    driver: bridge

volumes:
  neo4j-data:

